### ISSUE TITLE
Hardcoded backend URL

### ISSUE THREAD

**Issue by victorskl** [planimation/frontend#14]
Need to find way to export this hardcoded backend URL as environment variable.
Line 76 `frontend/Assets/Visualiser/Scripts/ScenesCoordinator.cs`

So that at runtime/deployment the specific environment variable will point to respective URL

**Comment by victorskl** [comment]
Temporary quick fix work for the moment. @rakeshchoyal92 Pls further investigate to see whether we can expose this as environment variable.

**Comment by ftdzh1994** [comment]
I try to deploy the newest version, and find the error connection between frontend and backend.
`2020/05/08 05:41:46 [error] 7#7: *3 open() "/usr/share/nginx/html/upload/pddl" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "POST /upload/pddl HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/`
This quick fix arouse error: the request goes to "/usr/share/nginx/html/upload/pddl"  instead of "serverURL:/upload/pddl".
If i want to deploy it successfully, I have to change back to the hard code, right?

**Comment by nirlipo** [comment]
Thanks @ftdzh1994 , please do a PR to close this issue.
